import fs from "node:fs/promises";
import { expect, test, type Page } from "@playwright/test";

async function exportState(page: Page, name: string) {
  await fs.mkdir(".e2e-tmp/design", { recursive: true });
  const html = await page.evaluate(() => {
    const clone = document.documentElement.cloneNode(true) as HTMLElement;
    clone.querySelectorAll("script").forEach(node => { node.remove(); });
    clone.querySelectorAll<HTMLLinkElement>("link[href]").forEach(node => { node.href = new URL(node.getAttribute("href") || "", location.href).href; });
    clone.querySelectorAll<HTMLImageElement>("img[src]").forEach(node => { node.src = new URL(node.getAttribute("src") || "", location.href).href; });
    const fields = [...document.querySelectorAll<HTMLInputElement>("input")];
    clone.querySelectorAll<HTMLInputElement>("input").forEach((node, i) => { node.value = fields[i]?.value || ""; if (fields[i]?.checked) node.setAttribute("checked", ""); else node.removeAttribute("checked"); });
    clone.querySelectorAll<HTMLTextAreaElement>("textarea").forEach((node, i) => { node.textContent = document.querySelectorAll<HTMLTextAreaElement>("textarea")[i]?.value || ""; });
    return `<!doctype html>${clone.outerHTML}`;
  });
  await fs.writeFile(`.e2e-tmp/design/${name}.html`, html);
  await page.screenshot({ path: `.e2e-tmp/design/${name}.png` });
}

test("approved workspace style: plus menu, real files, direct editor and compact send/stop", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("z-agent:theme", "light"));
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/");
  await page.getByRole("button", { name: "Регистрация" }).click();
  await page.locator("#email").fill(`design-${Date.now()}@example.com`);
  await page.locator("#password").fill("correct-horse");
  await page.locator("#confirm").fill("correct-horse");
  await page.getByRole("button", { name: "Зарегистрироваться" }).click();
  const composer = page.getByRole("textbox", { name: "Сообщение ассистенту" });
  await expect(composer).toBeVisible();
  const tour = page.getByRole("button", { name: "Пропустить знакомство" });
  if (await tour.isVisible()) await tour.click();
  await page.keyboard.press("Escape");
  const send = page.getByRole("button", { name: "Отправить сообщение" });
  const disc = send.locator(".composer-submit-disc");
  await expect(disc).toHaveCSS("width", "28px");
  await expect(send).toHaveCSS("width", "44px");
  await exportState(page, "empty-desktop");
  await page.getByRole("button", { name: "Добавить файлы, скиллы и инструменты" }).click();
  await expect(page.getByRole("menuitem", { name: "Добавить фото" })).toBeVisible();
  await exportState(page, "plus-desktop");
  await page.keyboard.press("Escape");
  await composer.fill("E2E fixture: create a tiny module, verify it with a regression test, and report completion.");
  await send.click();
  await expect(page.getByText(/Fixture task completed and verified: hello\.js/i)).toBeVisible({ timeout: 25_000 });
  await page.getByTestId("workspace-toggle").click();
  await expect(page.locator("#workspace-panel-files")).toBeVisible();
  await expect(page.locator(".agent-workspace [role=tablist]")).toHaveCount(0);
  // Create a real preview file in the disposable test user's workspace.
  await page.evaluate(async () => {
    const sessions = await fetch("/api/session", { credentials: "include" }).then(r => r.json());
    const sid = sessions[0]?.id;
    const res = await fetch(`/api/workspace/file?sessionId=${encodeURIComponent(sid)}`, { method: "PUT", credentials: "include", headers: { "Content-Type": "application/json", "x-csrf-token": decodeURIComponent(document.cookie.split(";").map(s => s.trim()).find(s => s.startsWith("z_agent_csrf="))?.split("=")[1] || "") }, body: JSON.stringify({ path: "index.html", content: '<!doctype html><html lang="ru"><meta charset="utf-8"><style>body{margin:0;background:#f7f7f2;color:#282926;font:16px/1.6 Arial;padding:28px}header{font-weight:bold;border-bottom:1px solid #deded8;padding-bottom:24px}h1{font:48px/1.15 Georgia;letter-spacing:-1.5px;margin-top:64px}.card{margin-top:36px;background:#e3e8da;padding:32px;border-radius:8px;font:80px Georgia}</style><header>north studio</header><h1>Делаем сложное простым.</h1><p>Создаём цифровые продукты,<br>которыми приятно пользоваться.</p><div class="card">n.</div></html>' }) });
    if (!res.ok) throw new Error(`preview fixture: ${res.status}`);
  });
  await page.getByRole("button", { name: "Обновить", exact: true }).click();
  await expect(page.locator("#workspace-panel-files").getByRole("button", { name: "index.html", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Открыть предпросмотр", exact: true }).click();
  await expect(page.locator("iframe[title=Предпросмотр]")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog", { name: "index.html" })).toHaveCount(0);
  await exportState(page, "workspace-desktop");
  await expect(page.getByRole("button", { name: "Новый файл", exact: true })).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Новая папка", exact: true })).toHaveCount(0);
  await expect(page.getByRole("searchbox", { name: "Поиск файлов" })).toHaveCount(0);
  await page.getByRole("button", { name: "Поиск файлов", exact: true }).click();
  const search = page.getByRole("searchbox", { name: "Поиск файлов" });
  await expect(search).toBeFocused();
  await expect(page.locator("#workspace-panel-files")).toBeVisible();
  await search.fill("index");
  await expect(page.locator("#workspace-panel-files").getByRole("button", { name: "index.html", exact: true })).toBeVisible();
  await exportState(page, "workspace-search-desktop");
  await page.getByRole("button", { name: "Закрыть поиск файлов" }).click();
  await expect(search).toHaveCount(0);
  await expect(page.getByRole("button", { name: "Поиск файлов", exact: true })).toBeFocused();
  await page.locator("#workspace-panel-files").getByRole("button", { name: "index.html", exact: true }).click();
  const editor = page.getByRole("region", { name: "index.html", exact: true });
  await expect(editor.locator("textarea")).toBeVisible();
  await expect(editor.locator("iframe")).toHaveCount(0);
  await exportState(page, "code-desktop");
  await page.getByRole("button", { name: "Добавить файлы, скиллы и инструменты" }).click();
  await page.getByRole("menuitem", { name: "Скиллы этого чата" }).click();
  await expect(page.getByRole("dialog", { name: "Скиллы этого чата" })).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(page.getByRole("region", { name: "index.html" })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: "Закрыть файлы проекта" }).click();
  await page.getByRole("button", { name: "Добавить файлы, скиллы и инструменты" }).click();
  await exportState(page, "plus-mobile");
  await page.keyboard.press("Escape");
  await page.getByTestId("workspace-toggle").click();
  await expect(page.locator("#workspace-panel-files")).toBeVisible();
  await expect(page.locator(".agent-workspace [role=tablist]")).toHaveCount(0);
  await exportState(page, "workspace-mobile");
  await page.getByRole("button", { name: "Поиск файлов", exact: true }).click();
  await expect(search).toBeFocused();
  await search.fill("hello");
  await exportState(page, "workspace-search-mobile");
  await page.locator("#workspace-panel-files").getByRole("button", { name: "hello.js", exact: true }).click();
  await expect(page.getByRole("region", { name: "hello.js" })).toBeVisible();
  await expect(search).toHaveCount(0);
  const fileEditor = page.getByRole("region", { name: "hello.js", exact: true });
  await expect(fileEditor.locator("textarea")).toBeVisible();
  await exportState(page, "code-mobile");
  await fileEditor.getByRole("button", { name: "Закрыть", exact: true }).click();
  await expect(page.locator("#workspace-panel-files")).toBeVisible();
  await expect(fileEditor).toHaveCount(0);
  await page.emulateMedia({ reducedMotion: "reduce" });
  await page.getByRole("button", { name: "Поиск файлов", exact: true }).click();
  await expect(search.locator("..")).toHaveCSS("animation-name", "none");
  await expect(search).toHaveValue("");
  await page.keyboard.press("Escape");
  await expect(page.getByRole("button", { name: "Поиск файлов", exact: true })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
